language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - pip install -r requirements.txt
  - sudo mkdir /etc/drone
  - sudo chown $(whoami) /etc/drone
  - sudo mkdir -p /usr/local/bin
  - sudo chown $(whoami) /usr/local/bin
  - sudo mkdir -p /var/drone
  - sudo chown $(whoami) /var/drone
  - mkdir -p /var/drone/metadata/
  - mkdir -p /var/drone/logs/
  - sudo mkdir -p /var/www/
  - sudo chown $(whoami) /var/www/
  - mkdir -p /var/www/js/foundation
  - mkdir -p /var/www/css
  - mkdir -p /var/www/images
install:
  - python setup.py -q install
script:
  - nosetests --collect-only