language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - pip install -r requirements.txt
  - sudo mkdir /etc/drone
  - sudo chown $(whoami) /etc/drone
  - sudo mkdir -p /var/drone/metadata/
  - sudo chown $(whoami) /var/drone/metadata/
  - sudo mkdir -p /var/drone/logs/
  - sudo chown $(whoami) /var/drone/logs/
install:
  - python setup.py -q install
script:
  - nosetests --collect-only